server:
  port: 8081
  tomcat:
    relaxedPathChars: '<,>,[,\,],^,`,{,|,}'
    relaxedQueryChars: '<,>,[,\,],^,`,{,|,}'
    max-http-form-post-size: 500MB
  max-http-header-size: 2048000


spring:
  application:
    name: bookstore-login
  # 配置数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 123456
  # 配置上传文件信息
  servlet:
    multipart:
      max-file-size: 100MB

#jdk:
#  tls:
#    disabledAlgorithms: SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024
#    client:
#      protocols: TLSv1.2,TLSv1.3

mybatis:
  # 配置实体类别名 包路径
  type-aliases-package: cn.ywrby.domain
  # 配置映射文件路径
  mapper-locations: classpath:mapper/*.xml
  # 配置日志文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  path: C:\DeepReaderArticleData\
